--- # Bootstrap Webservers
- hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    target_started: started

  tasks:
  - debug:
      var: target_service
  - name: latest httpd installed
    yum:
      name: "{{ target_service }}"
      state: latest
    notify: 
      - restart httpd
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "{{ ansible_hostname}}: here is some text"
      path: /var/www/html/index.html
    notify:
      - restart httpd
    register: task_debug 
  - debug:
      msg: "Output of lineinfile is: {{ task_debug }}"
  handlers:
  - name: start httpd
    service:
      name: httpd
      state: restarted
    listen: "restart httpd"
